FROM registry.access.redhat.com/ubi8/ubi-minimal:8.1

ENV mongodbHost='localhost'
ENV mongodbPort='27017'

WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/*-runner /work/application
COPY --chown=1001:root deployments/aiplatform.json /deployments/

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]