apiVersion: apps/v1
kind: Deployment
metadata:
  name: jennetwork-qa
  labels:
    app: jennetwork-qa
spec:
  selector:
    matchLabels:
      app: jennetwork-qa
  template:
    metadata:
      labels:
        app: jennetwork-qa
    spec:
      containers:
      - name: system-container
        image: gcr.io/appgallabs-271922/appgal-cloud:v1
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: system-service
spec:
  type: NodePort
  selector:
    app: system
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 31000
---
apiVersion: v1
kind: Service
metadata:
  name: jennetwork-qa
spec:
  type: NodePort
  selector:
    app: jennetwork-qa
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 30001