name: app
description: AppGal Labs, Food Recovery Optimization Network (FutureGeniuses)
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:
  flutter_localized_locales: ^1.1.0
  cupertino_icons: ^0.1.2
  google_maps_flutter: 0.5.24+1
  test: ^1.14.0
  dart_ui: ^0.1.3

dev_dependencies:
flutter_driver:
sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - fonts/google_fonts/
    - assets/demos/
    - assets/studies/
    - assets/icons/cupertino/
    - assets/icons/material/
    - assets/icons/reference/
    - assets/icons/settings/
    - assets/logo/
    - assets/splash_effects/
    - assets/crane/logo/
    - assets/crane/destinations/
    - assets/fortnightly/

  fonts:
    - family: GalleryIcons
      fonts:
        - asset: fonts/GalleryIcons.ttf
